In [ ]:
from scipy.spatial.transform import Rotation as R
import numpy as np
a = np.array([0,1,0])
R.from_rotvec(a).as_quat()

In [ ]:
theta = 3*np.pi/2
bb = np.array([0,1,0])*np.sin(theta/2)
w = np.cos(theta/2)
aa = np.array([bb[0],bb[1],bb[2],w])
r = R.from_quat(aa, scalar_first=False)
r.as_rotvec()

In [ ]:
# check for ill-conditioning by liinearly interpolating between two rotation vectors
from scipy.spatial.transform import Rotation as R
import numpy as np
ep = 1E-20
a = np.pi-ep
r1 = np.array([0,a,0])
r2 = np.array([0,-a,0])
interp = np.array([0.5,0.5])
rotation = np.array([r1,r2])
np.dot(interp, rotation)

array([0., 0., 0.])

In [8]:
# check for ill-conditioning by liinearly interpolating between two rotation vectors
from scipy.spatial.transform import Rotation as R
import numpy as np
ep = 1E-20
a = np.pi-ep
r1 = np.array([0,a,0])
r2 = np.array([0,-a,0])
interp = np.array([0.5,0.5])
RotN1 = R.from_rotvec(r1).as_matrix()
RotN2 = R.from_rotvec(r2).as_matrix()
Rotref = RotN1
RotPhy2 = R.from_matrix(Rotref.T @ RotN2).as_rotvec()
RotPhy1 = np.array([0,0,0])
rotation = np.array([RotPhy1,RotPhy2])
interpVec = np.dot(interp, rotation)
R.from_matrix(Rotref @ R.from_rotvec(interpVec).as_matrix()).as_rotvec()

array([0.        , 3.14159265, 0.        ])

In [6]:
RotPhy2

array([[ 1.0000000e+00,  0.0000000e+00,  2.4492936e-16],
       [ 0.0000000e+00,  1.0000000e+00,  0.0000000e+00],
       [-2.4492936e-16,  0.0000000e+00,  1.0000000e+00]])