In [1]:
from gen.gen_utilities import rotVecToQuat, quatToRotMat, rotMatToQuat, rotTensor, quatToRotVec
import numpy as np

In [2]:
# Test 0. - Indentity rotation
rotVec = np.array([0,0,0])
resultQat = np.array([1,0,0,0])
resultRotMat = np.eye(3)

quat = rotVecToQuat(rotVec)
vec = quatToRotVec(quat)
rotMat = quatToRotMat(quat)

print("Test 0 - Identity rotation")
print('Quaternion:', quat)
print('Rotation Matrix:', rotMat)
print('Quaternion from rotation matrix:', rotMatToQuat(rotMat))
print('Vector from quaternion:', vec)

error = resultRotMat.T @ rotMat
print('Error in rotation matrix:', error)

normRotVec= 0.0
Test 0 - Identity rotation
Quaternion: [1. 0. 0. 0.]
Rotation Matrix: [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Quaternion from rotation matrix: [1. 0. 0. 0.]
Vector from quaternion: [0. 0. 0.]
Error in rotation matrix: [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [3]:
a = rotTensor(rotVec=rotVec)
print('Rotation tensor from Scipy rotation function:', a)
if np.isclose(a, rotMat).all():
    print('SciPy rotation tensor matches rotation matrix.')

Rotation tensor from Scipy rotation function: [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
SciPy rotation tensor matches rotation matrix.


In [4]:
# Test 1 - 90deg rotation about x axis
rotVec = np.array([np.pi/2,0,0])
resultQat = np.array([0.7071067811865476,0.7071067811865476,0,0])
resultRotMat = np.array([[1,0,0],[0,0,-1],[0,1,0]])

quat = rotVecToQuat(rotVec)
vec = quatToRotVec(quat)
rotMat = quatToRotMat(quat)

print("Test 0 - Identity rotation")
print('Quaternion:', quat)
print('Rotation Matrix:', rotMat)
print('Quaternion from rotation matrix:', rotMatToQuat(rotMat))
print('Vector from quaternion:', vec)

error = resultRotMat.T @ rotMat
print('Error in rotation matrix:', error)

normRotVec= 1.5707963267948966
Test 0 - Identity rotation
Quaternion: [0.70710678 0.70710678 0.         0.        ]
Rotation Matrix: [[ 1.  0.  0.]
 [ 0.  0. -1.]
 [ 0.  1.  0.]]
Quaternion from rotation matrix: [0.70710678 0.70710678 0.         0.        ]
Vector from quaternion: [1.57079633 0.         0.        ]
Error in rotation matrix: [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [5]:
a = rotTensor(rotVec=rotVec)
print('Rotation tensor from Scipy rotation function:', a)
if np.isclose(a, rotMat).all():
    print('SciPy rotation tensor matches rotation matrix.')

Rotation tensor from Scipy rotation function: [[ 1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  2.22044605e-16 -1.00000000e+00]
 [ 0.00000000e+00  1.00000000e+00  2.22044605e-16]]
SciPy rotation tensor matches rotation matrix.


In [6]:
# Test 2 - 90deg rotation about y axis
rotVec = np.array([0,np.pi/2,0])
resultQat = np.array([0.7071067811865476,0,0.7071067811865476,0])
resultRotMat = np.array([[0,0,1],[0,1,0],[-1,0,0]])

quat = rotVecToQuat(rotVec)
vec = quatToRotVec(quat)
rotMat = quatToRotMat(quat)

print("Test 0 - Identity rotation")
print('Quaternion:', quat)
print('Rotation Matrix:', rotMat)
print('Quaternion from rotation matrix:', rotMatToQuat(rotMat))
print('Vector from quaternion:', vec)

error = resultRotMat.T @ rotMat
print('Error in rotation matrix:', error)

normRotVec= 1.5707963267948966
Test 0 - Identity rotation
Quaternion: [0.70710678 0.         0.70710678 0.        ]
Rotation Matrix: [[ 0.  0.  1.]
 [ 0.  1.  0.]
 [-1.  0.  0.]]
Quaternion from rotation matrix: [0.70710678 0.         0.70710678 0.        ]
Vector from quaternion: [0.         1.57079633 0.        ]
Error in rotation matrix: [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [7]:
a = rotTensor(rotVec=rotVec)
print('Rotation tensor from Scipy rotation function:', a)
if np.isclose(a, rotMat).all():
    print('SciPy rotation tensor matches rotation matrix.')

Rotation tensor from Scipy rotation function: [[ 2.22044605e-16  0.00000000e+00  1.00000000e+00]
 [ 0.00000000e+00  1.00000000e+00  0.00000000e+00]
 [-1.00000000e+00  0.00000000e+00  2.22044605e-16]]
SciPy rotation tensor matches rotation matrix.


In [8]:
# Test 3 - arbitrary rotation - 30deg

np.set_printoptions(precision=10, suppress=True)
angle = 0.5235987755982988
axis = np.array([1,2,3])/np.sqrt(14)
rotVec = angle * axis
resultQat = np.array([0.9659258262890683, 0.0691515329339893, 0.1383030658679786, 0.2074545988019679])
resultRotMat = np.array([[ 0.93581285, -0.24438531,  0.25736183],
                        [ 0.26435732,  0.96341214, -0.04374382],
                        [-0.23739182,  0.11075306,  0.96502804]])

quat = rotVecToQuat(rotVec)
vec = quatToRotVec(quat)
rotMat = quatToRotMat(quat)

print("Test 0 - Identity rotation")
print('Quaternion:', quat)
print('Rotation Matrix:', rotMat)
print('Quaternion from rotation matrix:', rotMatToQuat(rotMat))
print('Vector from quaternion:', vec)

error = resultRotMat.T @ rotMat
print('Error in rotation matrix:', error)

normRotVec= 0.5235987755982988
Test 0 - Identity rotation
Quaternion: [0.9659258263 0.0691722994 0.1383445988 0.2075168983]
Rotation Matrix: [[ 0.8755950178 -0.3817526348  0.295970084 ]
 [ 0.4200310909  0.9043038598 -0.0762129369]
 [-0.2385523999  0.191048305   0.9521519299]]
Quaternion from rotation matrix: [0.9659258263 0.0691722994 0.1383445988 0.2075168983]
Vector from quaternion: [0.139937659  0.2798753181 0.4198129771]
Error in rotation matrix: [[ 0.9870617509 -0.1635429812  0.0307920805]
 [ 0.164260084   0.9856712372 -0.0403014695]
 [-0.0232387832  0.0465607094  0.9983585581]]


In [9]:
a = rotTensor(rotVec=rotVec)
print('Rotation tensor from Scipy rotation function:', a)
if np.isclose(a, rotMat).all():
    print('SciPy rotation tensor matches rotation matrix.')

Rotation tensor from Scipy rotation function: [[ 0.8755950178 -0.3817526348  0.295970084 ]
 [ 0.4200310909  0.9043038598 -0.0762129369]
 [-0.2385523999  0.191048305   0.9521519299]]
SciPy rotation tensor matches rotation matrix.


Large error found between rotation matrix, obtained from genAI vs calculated. However calcualted value matches rotation tensor calcualted from Scipy.

In [10]:
# Test 4 - arbitrary rotation - 1.1 radian

angle = 1.1
axis = np.array([0.2672612419,0.5345224838,0.8017837257])
rotVec = angle * axis
resultQat = np.array([0.8525245220595057, 0.139648,0.279296,0.418944])
resultRotMat = np.array([[ 0.4920, -0.6357, 0.5942], 
                        [0.7927, 0.6092, 0.0218],
                        [-0.3614, 0.4755, 0.8010]])

quat = rotVecToQuat(rotVec)
vec = quatToRotVec(quat)
rotMat = quatToRotMat(quat)

print("Test 0 - Identity rotation")
print('Quaternion:', quat)
print('Rotation Matrix:', rotMat)
print('Quaternion from rotation matrix:', rotMatToQuat(rotMat))
print('Vector from quaternion:', vec)

error = resultRotMat.T @ rotMat
print('Error in rotation matrix:', error)

normRotVec= 1.0999999999488634
Test 0 - Identity rotation
Quaternion: [0.8525245221 0.1396940379 0.2793880759 0.4190821138]
Rotation Matrix: [[ 0.4926249699 -0.6364978606  0.5934569171]
 [ 0.7926132545  0.6097115153 -0.004012095 ]
 [-0.3592838263  0.4723582766  0.8048557577]]
Quaternion from rotation matrix: [0.8525245221 0.1396940379 0.2793880759 0.4190821138]
Vector from quaternion: [0.2939873661 0.5879747322 0.8819620983]
Error in rotation matrix: [[ 1.0005211868 -0.0005489104 -0.0020744554]
 [-0.0011411582  1.0006643057  0.0030041823]
 [ 0.0222103812  0.0134436619  0.9972340984]]


In [11]:
a = rotTensor(rotVec=rotVec)
print('Rotation tensor from Scipy rotation function:', a)
if np.isclose(a, rotMat).all():
    print('SciPy rotation tensor matches rotation matrix.')

Rotation tensor from Scipy rotation function: [[ 0.4926249699 -0.6364978606  0.5934569171]
 [ 0.7926132545  0.6097115153 -0.004012095 ]
 [-0.3592838263  0.4723582766  0.8048557577]]
SciPy rotation tensor matches rotation matrix.


Large error found between rotation matrix, obtained from genAI vs calculated. However calcualted value matches rotation tensor calcualted from Scipy.

In [12]:
# Test 5 - 180degree about X axis
angle = 3.141592653589793
axis = np.array([1,0,0])
rotVec = angle * axis
resultQat = np.array([0, 1, 0, 0])
resultRotMat = np.array([[ 1, 0, 0], 
                        [0, -1, 0],
                        [0, 0, -1]])

quat = rotVecToQuat(rotVec)
vec = quatToRotVec(quat)
rotMat = quatToRotMat(quat)

print("Test 0 - Identity rotation")
print('Quaternion:', quat)
print('Rotation Matrix:', rotMat)
print('Quaternion from rotation matrix:', rotMatToQuat(rotMat))
print('Vector from quaternion:', vec)

error = resultRotMat.T @ rotMat
print('Error in rotation matrix:', error)

normRotVec= 3.141592653589793
Test 0 - Identity rotation
Quaternion: [0. 1. 0. 0.]
Rotation Matrix: [[ 1.  0.  0.]
 [ 0. -1.  0.]
 [ 0.  0. -1.]]
Quaternion from rotation matrix: [0. 1. 0. 0.]
Vector from quaternion: [3.1415926536 0.           0.          ]
Error in rotation matrix: [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [13]:
a = rotTensor(rotVec=rotVec)
print('Rotation tensor from Scipy rotation function:', a)
if np.isclose(a, rotMat).all():
    print('SciPy rotation tensor matches rotation matrix.')

Rotation tensor from Scipy rotation function: [[ 1.  0.  0.]
 [ 0. -1. -0.]
 [ 0.  0. -1.]]
SciPy rotation tensor matches rotation matrix.


In [14]:
# Test 6 - 180degree about Y axis
angle = 3.141592653589793
axis = np.array([0,1,0])
rotVec = angle * axis
resultQat = np.array([0, 0, 1, 0])
resultRotMat = np.array([[ -1, 0, 0], 
                        [0, 1, 0],
                        [0, 0, -1]])

quat = rotVecToQuat(rotVec)
vec = quatToRotVec(quat)
rotMat = quatToRotMat(quat)

print("Test 0 - Identity rotation")
print('Quaternion:', quat)
print('Rotation Matrix:', rotMat)
print('Quaternion from rotation matrix:', rotMatToQuat(rotMat))
print('Vector from quaternion:', vec)

error = resultRotMat.T @ rotMat
print('Error in rotation matrix:', error)

normRotVec= 3.141592653589793
Test 0 - Identity rotation
Quaternion: [0. 0. 1. 0.]
Rotation Matrix: [[-1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0. -1.]]
Quaternion from rotation matrix: [0. 0. 1. 0.]
Vector from quaternion: [0.           3.1415926536 0.          ]
Error in rotation matrix: [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [15]:
a = rotTensor(rotVec=rotVec)
print('Rotation tensor from Scipy rotation function:', a)
if np.isclose(a, rotMat).all():
    print('SciPy rotation tensor matches rotation matrix.')

Rotation tensor from Scipy rotation function: [[-1.  0.  0.]
 [ 0.  1.  0.]
 [-0.  0. -1.]]
SciPy rotation tensor matches rotation matrix.


In [16]:
# Test 7 - 180degree about Z axis
angle = 3.141592653589793
axis = np.array([0,0,1])
rotVec = angle * axis
resultQat = np.array([0, 0, 1, 0])
resultRotMat = np.array([[ -1, 0, 0], 
                        [0, -1, 0],
                        [0, 0, 1]])

quat = rotVecToQuat(rotVec)
vec = quatToRotVec(quat)
rotMat = quatToRotMat(quat)

print("Test 0 - Identity rotation")
print('Quaternion:', quat)
print('Rotation Matrix:', rotMat)
print('Quaternion from rotation matrix:', rotMatToQuat(rotMat))
print('Vector from quaternion:', vec)

error = resultRotMat.T @ rotMat
print('Error in rotation matrix:', error)

normRotVec= 3.141592653589793
Test 0 - Identity rotation
Quaternion: [0. 0. 0. 1.]
Rotation Matrix: [[-1.  0.  0.]
 [ 0. -1.  0.]
 [ 0.  0.  1.]]
Quaternion from rotation matrix: [0. 0. 0. 1.]
Vector from quaternion: [0.           0.           3.1415926536]
Error in rotation matrix: [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [17]:
a = rotTensor(rotVec=rotVec)
print('Rotation tensor from Scipy rotation function:', a)
if np.isclose(a, rotMat).all():
    print('SciPy rotation tensor matches rotation matrix.')

Rotation tensor from Scipy rotation function: [[-1. -0.  0.]
 [ 0. -1.  0.]
 [ 0.  0.  1.]]
SciPy rotation tensor matches rotation matrix.


In [18]:
# Test 8 - 180 degree about arbitrary direction (off-plane)
angle = 3.141592653589793
axis = np.array([1/np.sqrt(2),1/np.sqrt(2),0])
rotVec = angle * axis
resultQat = np.array([0, 0.7071067811865476, 0.7071067811865476, 0])
resultRotMat = np.array([[ 0, 1, 0], 
                        [1, 0, 0],
                        [0, 0, -1]])

quat = rotVecToQuat(rotVec)
vec = quatToRotVec(quat)
rotMat = quatToRotMat(quat)

print("Test 0 - Identity rotation")
print('Quaternion:', quat)
print('Rotation Matrix:', rotMat)
print('Quaternion from rotation matrix:', rotMatToQuat(rotMat))
print('Vector from quaternion:', vec)

error = resultRotMat.T @ rotMat
print('Error in rotation matrix:', error)

normRotVec= 3.141592653589793
Test 0 - Identity rotation
Quaternion: [0.           0.7071067812 0.7071067812 0.          ]
Rotation Matrix: [[ 0.  1.  0.]
 [ 1.  0.  0.]
 [ 0.  0. -1.]]
Quaternion from rotation matrix: [0.           0.7071067812 0.7071067812 0.          ]
Vector from quaternion: [2.2214414691 2.2214414691 0.          ]
Error in rotation matrix: [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [19]:
a = rotTensor(rotVec=rotVec)
print('Rotation tensor from Scipy rotation function:', a)
if np.isclose(a, rotMat).all():
    print('SciPy rotation tensor matches rotation matrix.')

Rotation tensor from Scipy rotation function: [[ 0.  1.  0.]
 [ 1.  0. -0.]
 [-0.  0. -1.]]
SciPy rotation tensor matches rotation matrix.


In [20]:
# Test 9 - close to 180 degree about Z axis
angle = 3.141592653589793 - 1E-6
axis = np.array([0,0,1])
rotVec = angle * axis
resultQat = np.array([5E-7, 0, 0, 0.999999999999875])
resultRotMat = np.array([[ -0.9999999999995, -0.000001, 0], 
                        [0.000001, -0.9999999999995, 0],
                        [0, 0, 1]])

quat = rotVecToQuat(rotVec)
vec = quatToRotVec(quat)
rotMat = quatToRotMat(quat)

print("Test 0 - Identity rotation")
print('Quaternion:', quat)
print('Rotation Matrix:', rotMat)
print('Quaternion from rotation matrix:', rotMatToQuat(rotMat))
print('Vector from quaternion:', vec)

error = resultRotMat.T @ rotMat
print('Error in rotation matrix:', error)

normRotVec= 3.141591653589793
Test 0 - Identity rotation
Quaternion: [0.0000005 0.        0.        1.       ]
Rotation Matrix: [[-1.       -0.000001  0.      ]
 [ 0.000001 -1.        0.      ]
 [ 0.        0.        1.      ]]
Quaternion from rotation matrix: [0.0000005 0.        0.        1.       ]
Vector from quaternion: [0.           0.           3.1415916536]
Error in rotation matrix: [[ 1.  0.  0.]
 [-0.  1.  0.]
 [ 0.  0.  1.]]


In [21]:
a = rotTensor(rotVec=rotVec)
print('Rotation tensor from Scipy rotation function:', a)
if np.isclose(a, rotMat).all():
    print('SciPy rotation tensor matches rotation matrix.')

Rotation tensor from Scipy rotation function: [[-1.       -0.000001  0.      ]
 [ 0.000001 -1.        0.      ]
 [ 0.        0.        1.      ]]
SciPy rotation tensor matches rotation matrix.


In [22]:
# Test 10 - 360 deg rotation about X axis
angle = 2*np.pi
axis = np.array([1,0,0])
rotVec = angle * axis
resultQat = np.array([-1, 0, 0, 0])
resultRotMat = np.array([[1, 0, 0], 
                        [0, 1, 0],
                        [0, 0, 1]])

quat = rotVecToQuat(rotVec)
vec = quatToRotVec(quat)
rotMat = quatToRotMat(quat)

print("Test 0 - Identity rotation")
print('Quaternion:', quat)
print('Rotation Matrix:', rotMat)
print('Quaternion from rotation matrix:', rotMatToQuat(rotMat))
print('Vector from quaternion:', vec)

error = resultRotMat.T @ rotMat
print('Error in rotation matrix:', error)
print('This examples demonstrates the 2 to 1 relation between quaternion and rotation matrix representations of rotations.')

normRotVec= 6.283185307179586
Test 0 - Identity rotation
Quaternion: [-1.  0.  0.  0.]
Rotation Matrix: [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Quaternion from rotation matrix: [1. 0. 0. 0.]
Vector from quaternion: [0. 0. 0.]
Error in rotation matrix: [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
This examples demonstrates the 2 to 1 relation between quaternion and rotation matrix representations of rotations.


In [23]:
a = rotTensor(rotVec=rotVec)
print('Rotation tensor from Scipy rotation function:', a)
if np.isclose(a, rotMat).all():
    print('SciPy rotation tensor matches rotation matrix.')

Rotation tensor from Scipy rotation function: [[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0. -0.  1.]]
SciPy rotation tensor matches rotation matrix.


In [24]:
# Test 11 - >360 deg rotation about Z axis
angle = 7.853981633974483
axis = np.array([0,0,1])
rotVec = angle * axis
resultQat = np.array([-0.7071067811865476, 0, 0, -0.7071067811865476])
resultRotMat = np.array([[0, -1, 0], 
                        [1, 0, 0],
                        [0, 0, 1]])

quat = rotVecToQuat(rotVec)
vec = quatToRotVec(quat)
rotMat = quatToRotMat(quat)

print("Test 0 - Identity rotation")
print('Quaternion:', quat)
print('Rotation Matrix:', rotMat)
print('Quaternion from rotation matrix:', rotMatToQuat(rotMat))
print('Vector from quaternion:', vec)

error = resultRotMat.T @ rotMat
print('Error in rotation matrix:', error)
print('This examples demonstrates the 2 to 1 relation between quaternion and rotation matrix representations of rotations.')

normRotVec= 7.853981633974483
Test 0 - Identity rotation
Quaternion: [-0.7071067812  0.            0.           -0.7071067812]
Rotation Matrix: [[ 0. -1.  0.]
 [ 1.  0.  0.]
 [ 0.  0.  1.]]
Quaternion from rotation matrix: [0.7071067812 0.           0.           0.7071067812]
Vector from quaternion: [ 0.            0.           -4.7123889804]
Error in rotation matrix: [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
This examples demonstrates the 2 to 1 relation between quaternion and rotation matrix representations of rotations.


In [25]:
a = rotTensor(rotVec=rotVec)
print('Rotation tensor from Scipy rotation function:', a)
if np.isclose(a, rotMat).all():
    print('SciPy rotation tensor matches rotation matrix.')

Rotation tensor from Scipy rotation function: [[ 0. -1.  0.]
 [ 1.  0.  0.]
 [ 0.  0.  1.]]
SciPy rotation tensor matches rotation matrix.
