In [3]:
from scipy.spatial.transform import Rotation as R
import numpy as np
ep = np.pi/2
angle1 = np.pi
angle2 = ep
a = np.array([0,1,0])
vektor = R.from_matrix(R.from_rotvec(angle1*a).as_matrix() @ R.from_rotvec(angle2*a).as_matrix()).as_rotvec()
print(vektor)

[-0.         -1.57079633 -0.        ]


In [5]:
from gen.gen_utilities import rotVecCheck
R.from_rotvec(rotVecCheck(vektor)).as_matrix()

array([[ 8.8817842e-16,  0.0000000e+00, -1.0000000e+00],
       [ 0.0000000e+00,  1.0000000e+00,  0.0000000e+00],
       [ 1.0000000e+00,  0.0000000e+00,  8.8817842e-16]])

In [6]:
R.from_rotvec(vektor).as_matrix()

array([[-6.10622664e-16,  0.00000000e+00, -1.00000000e+00],
       [ 0.00000000e+00,  1.00000000e+00,  0.00000000e+00],
       [ 1.00000000e+00,  0.00000000e+00, -6.10622664e-16]])

In [10]:
b = np.array([0,0,1])
c = np.array([0,1,0])
bb = R.from_rotvec(b/np.linalg.norm(b)).as_matrix()
cc = R.from_rotvec(c/np.linalg.norm(c)).as_matrix()
d = R.from_matrix( bb @ cc ).as_rotvec()
print(d)
np.linalg.norm(d, ord=2)

[-0.49851154  0.91251925  0.91251925]


np.float64(1.3834364814420916)

In [17]:
R.from_matrix( bb @ cc ).as_matrix()

array([[ 0.29192658, -0.84147098,  0.45464871],
       [ 0.45464871,  0.54030231,  0.70807342],
       [-0.84147098,  0.        ,  0.54030231]])

In [11]:
rfg =[]
len(rfg)

0