In [2]:
from gen.gen_utilities import *
import numpy as np


In [3]:
print(rotationTensor_Mat(np.array([[0,0,0],[0,0,-1],[0,1,0]])*0))

[[nan nan nan]
 [nan nan nan]
 [nan nan nan]]


Cannot handle 0deg rotation - returns NAN values.
For other n*pi angles that sine or cosine functions return zero value, the function returns a very small value of the order of E-16 and not zero exactly.

In [2]:
print(rotationTensor_Vec(np.array([1,0,0])*0))

[[nan nan nan]
 [nan nan nan]
 [nan nan nan]]


/Users/kartikayshukla/Desktop/GRA/Models/FEM Models/Simo's static model/gen/gen_utilities.py:161: RuntimeWarning: invalid value encountered in scalar divide
  rotationTensor = I + (np.sin(normRotVec)/normRotVec)*skewMat + (2*np.square(np.sin(normRotVec/2)/normRotVec))*np.dot(skewMat,skewMat)


Cannot handle 0deg rotation - returns NAN values.
For other n*pi angles that sine or cosine functions return zero value, the function returns a very small value of the order of E-16 and not zero exactly.

In [3]:
print(rotTensor(np.array([1,0,0])*0))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


For n*pi angles that sine or cosine functions return zero value, the function returns a very small value of the order of E-16 and not zero exactly.

In [5]:
print(rotTensor(np.array([1,0,0])*4*np.pi))

[[ 1.0000000e+00  0.0000000e+00  0.0000000e+00]
 [ 0.0000000e+00  1.0000000e+00  4.8985872e-16]
 [ 0.0000000e+00 -4.8985872e-16  1.0000000e+00]]


In [7]:
x = rotTensor(np.array([1,0,0])*4*np.pi)
rotVector(x)

array([-4.8985872e-16,  0.0000000e+00,  0.0000000e+00])

In [6]:
print(rotationTensor_Vec(np.array([1,0,0])*4*np.pi))

[[ 1.0000000e+00  0.0000000e+00  0.0000000e+00]
 [ 0.0000000e+00  1.0000000e+00  4.8985872e-16]
 [ 0.0000000e+00 -4.8985872e-16  1.0000000e+00]]


In [ ]:
print(rotationTensor_Vec(np.array([1,0,0])*4*np.pi))