In [1]:
from main import *

inMatModF= [[4.80e+13 0.00e+00 0.00e+00]
 [0.00e+00 4.80e+13 0.00e+00]
 [0.00e+00 0.00e+00 5.25e+08]]
loadStep= 0
iterCount= 0
self.changeConfig[4][self.ECON[0]= [0. 0.]
effectwt= 1.0
S0= [0.5 0.5]
S1= [-1.  1.]
outerS= {'S00': array([[0.25, 0.25],
       [0.25, 0.25]]), 'S01': array([[-0.5,  0.5],
       [-0.5,  0.5]]), 'S10': array([[-0.5, -0.5],
       [ 0.5,  0.5]]), 'S11': array([[ 1., -1.],
       [-1.,  1.]])}
nu= [[0. 0.]
 [0. 0.]
 [0. 0.]]
nuGP= [0. 0. 0.]
diffNuGP= [0. 0. 0.]
normNu= 0.0
gamma= [0. 0. 0.]
omega= [[[0. 0. 0.]]]
self.dphi_oE= [0. 0. 1.]
self.permutation[:,0,:]= [[ 0.  0.  0.]
 [ 0.  0. -1.]
 [ 0.  1.  0.]]
termIa= [0.0e+00 4.8e+13 0.0e+00]
termIa= [0. 1. 0.]
termII= [[ 109374.93 -109374.93]
 [-109374.93  109374.93]]
self.permutation[:,1,:]= [[ 0.  0.  1.]
 [ 0.  0.  0.]
 [-1.  0.  0.]]
termIa= [0.0e+00 4.8e+13 0.0e+00]
termIa= [-1.  0.  0.]
termII= [[ 0. -0.]
 [-0.  0.]]
self.permutation[:,2,:]= [[ 0. -1.  0.]
 [ 1.  0.  0.]
 [ 0.  0.  0.]]
termIa= [0.0e+00 4.8

/opt/miniconda3/envs/Fenics_env/lib/python3.13/site-packages/scipy/sparse/_index.py:210: SparseEfficiencyWarning: Changing the sparsity structure of a csr_matrix is expensive. lil and dok are more efficient.
  self._set_arrayXarray(i, j, x)


In [19]:
from gen.gen_utilities import *
a = np.array([0,-0.01556701,0])
b = rotTensor(a)
c = np.array([0,0.01239586,0])
d = rotTensor(c)
e = d @ b
print(e)
rotVector(e)

[[ 0.99999497  0.         -0.00317114]
 [ 0.          1.          0.        ]
 [ 0.00317114  0.          0.99999497]]


array([ 0.        , -0.00317115,  0.        ])

In [7]:
from gen.gen_utilities import *
a = np.array([1.11072073,1.11072073,0]) * 0.5
b = rotTensor(a)
c = b @ np.array([[2,        0,        0,       ],
 [0,        2,        0,       ],
 [0,        0,        1.5238088]]) @ b.T
b @ np.array([[2.985728e+12 ,0.000000e+00, 0.000000e+00],
 [0.000000e+00, 2.985728e+12, 0.000000e+00],
 [0.000000e+00, 0.000000e+00, 2.299017e+06]]) @ b.T @ np.array([0.05536037, -0.05536037 , 0.29289322])

array([-2.26536453e+11,  2.26536453e+11,  3.20371776e+11])

In [8]:
c @ np.array([2.22144147, 2.22144147 ,0        ])

array([4.44288294e+00, 4.44288294e+00, 2.61019050e-17])

In [21]:
80E9 * 5.20833E-7 *2

83333.28

In [23]:
from gen.gen_utilities import *
permutation_symbol()[:,0,:]

array([[ 0.,  0.,  0.],
       [ 0.,  0., -1.],
       [ 0.,  1.,  0.]])