In [1]:
from main import *

0
self.S[S1]= [-0.2  0.2]
self.phi_o[self.ECON[i],:]= [[0. 0. 0.]
 [0. 0. 5.]]
self.dphi_oE= [0. 0. 1.]
self.momentGP= [0. 0. 0.]
self.matModMGP= [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
self.forceGP= [0. 0. 0.]
1
self.S[S1]= [-0.2  0.2]
self.phi_o[self.ECON[i],:]= [[ 0.  0.  5.]
 [ 0.  0. 10.]]
self.dphi_oE= [0. 0. 1.]
self.momentGP= [0. 0. 0.]
self.matModMGP= [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
self.forceGP= [0. 0. 0.]
det SMG= 0.0
rank SMG= 11
solution= [nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan]
self.rotVec[change]= [nan nan nan]
rotMat[prev]= [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
rotMat[change]= [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
rotMat[new]= [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]


/opt/miniconda3/envs/Fenics_env/lib/python3.13/site-packages/scipy/sparse/_index.py:210: SparseEfficiencyWarning: Changing the sparsity structure of a csr_matrix is expensive. lil and dok are more efficient.
  self._set_arrayXarray(i, j, x)
/Users/kartikayshukla/Desktop/GRA/Models/FEM Models/Simo's static model/solver.py:370: MatrixRankWarning: Matrix is exactly singular
  self.solution[:] = spsolve(self.SMG, self.CVG)
/opt/miniconda3/envs/Fenics_env/lib/python3.13/site-packages/numpy/linalg/_linalg.py:2431: RuntimeWarning: invalid value encountered in det
  r = _umath_linalg.det(a, signature=signature)


LinAlgError: SVD did not converge

In [ ]:
a

In [ ]:
import numpy as np
a = np.array([[4.2,0    ,0   ,0    ,0    ,0    ,0    ,0   ,0    ,0    ,0    ,0   ,0   ,0    ,0    ],
              [0  ,4.2  ,0   ,-10.5,0    ,0    ,-4.2 ,0   ,-10.5,0    ,0    ,0   ,0   ,0    ,0    ],
              [0  ,0    ,4.2 ,0    ,0    ,0    ,0    ,-4.2,0    ,0    ,0    ,0   ,0   ,0    ,0    ],
              [0  ,-10.5,0   ,26.25,0    ,0    ,10.5 ,0   ,26.25,0    ,0    ,0   ,0   ,0    ,0    ],
              [0  ,0    ,0   ,0    ,26.25,-10.5,0    ,0   ,0    ,26.25,0    ,0   ,0   ,0    ,0    ],
              [0  ,0    ,0   ,0    ,-10.5,8.4  ,0    ,0   ,0    ,0    ,-4.2 ,0   ,0   ,0    ,10.5 ],
              [0  ,-4.2 ,0   ,10.5 ,0    ,0    ,8.4  ,0   ,0    ,0    ,0    ,-4.2,0   ,-10.5,0    ],
              [0  ,0    ,-4.2,0    ,0    ,0    ,0    ,8.4 ,0    ,0    ,0    ,0   ,-4.2,0    ,0    ],
              [0  ,-10.5,0   ,26.25,0    ,0    ,0    ,0   ,52.5 ,0    ,0    ,10.5,0   ,26.25,0    ],
              [0  ,0    ,0   ,0    ,26.25,0    ,0    ,0   ,0    ,52.5 ,-10.5,0   ,0   ,0    ,26.25],
              [0  ,0    ,0   ,0    ,0    ,-4.2 ,0    ,0   ,0    ,-10.5,4.2  ,0   ,0   ,0    ,-10.5],
              [0  ,0    ,0   ,0    ,0    ,0    ,-4.2 ,0   ,10.5 ,0    ,0    ,4.2 ,0   ,10.5 ,0    ],
              [0  ,0    ,0   ,0    ,0    ,0    ,0    ,-4.2,0    ,0    ,0    ,0   ,4.2 ,0    ,0    ],
              [0  ,0    ,0   ,0    ,0    ,0    ,-10.5,0   ,26.25,0    ,0    ,10.5,0   ,26.25,0    ],
              [0  ,0    ,0   ,0    ,0    ,10.5 ,0    ,0   ,0    ,26.25,-10.5,0   ,0   ,0    ,26.25],
              ]) * 1E10


np.linalg.det(a)

# b = np.array([0,0,0,0,0,0,0,0,0,0,-500,0,0,0,0]) 
# np.linalg.solve(a,b)

In [ ]:
np.linalg.matrix_rank(a)

In [ ]:
from gen.gen_utilities import *
x = permutation_symbol()
x[:,2,:]

array([[ 0., -1.,  0.],
       [ 1.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [9]:
import numpy as np
K = {
    'K00': np.zeros(shape=[2,2],dtype=np.float64),
    'K01': np.ones(shape=[2,2],dtype=np.float64) * 1 ,
    'K02': np.ones(shape=[2,2],dtype=np.float64) * 2 ,
    'K03': np.ones(shape=[2,2],dtype=np.float64) * 3 ,
    'K04': np.ones(shape=[2,2],dtype=np.float64) * 4 ,
    'K05': np.ones(shape=[2,2],dtype=np.float64) * 5 ,
    'K10': np.ones(shape=[2,2],dtype=np.float64) * 6 ,
    'K11': np.ones(shape=[2,2],dtype=np.float64) * 7 ,
    'K12': np.ones(shape=[2,2],dtype=np.float64) * 8 ,
    'K13': np.ones(shape=[2,2],dtype=np.float64) * 9 ,
    'K14': np.ones(shape=[2,2],dtype=np.float64) * 10 ,
    'K15': np.ones(shape=[2,2],dtype=np.float64) * 11,
    'K20': np.ones(shape=[2,2],dtype=np.float64) * 12,
    'K21': np.ones(shape=[2,2],dtype=np.float64) * 13,
    'K22': np.ones(shape=[2,2],dtype=np.float64) * 14,
    'K23': np.ones(shape=[2,2],dtype=np.float64) * 15,
    'K24': np.ones(shape=[2,2],dtype=np.float64) * 16,
    'K25': np.ones(shape=[2,2],dtype=np.float64) * 17,
    'K30': np.ones(shape=[2,2],dtype=np.float64) * 18,
    'K31': np.ones(shape=[2,2],dtype=np.float64) * 19,
    'K32': np.ones(shape=[2,2],dtype=np.float64) * 20,
    'K33': np.ones(shape=[2,2],dtype=np.float64) * 21,
    'K34': np.ones(shape=[2,2],dtype=np.float64) * 22,
    'K35': np.ones(shape=[2,2],dtype=np.float64) * 23,
    'K40': np.ones(shape=[2,2],dtype=np.float64) * 24,
    'K41': np.ones(shape=[2,2],dtype=np.float64) * 25,
    'K42': np.ones(shape=[2,2],dtype=np.float64) * 26,
    'K43': np.ones(shape=[2,2],dtype=np.float64) * 27,
    'K44': np.ones(shape=[2,2],dtype=np.float64) * 28,
    'K45': np.ones(shape=[2,2],dtype=np.float64) * 29,
    'K50': np.ones(shape=[2,2],dtype=np.float64) * 30,
    'K51': np.ones(shape=[2,2],dtype=np.float64) * 31,
    'K52': np.ones(shape=[2,2],dtype=np.float64) * 32,
    'K53': np.ones(shape=[2,2],dtype=np.float64) * 33,
    'K54': np.ones(shape=[2,2],dtype=np.float64) * 34,
    'K55': np.ones(shape=[2,2],dtype=np.float64) * 35
}

In [10]:
coeffSME = np.zeros(shape=[12,12],dtype=np.float64)
for j in range(6):
    for k in range(6):
        coeffSME[j:12:6, k:12:6] = K[f'K{j}{k}']

In [11]:
coeffSME

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  0.,  1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10., 11.,  6.,  7.,  8.,  9., 10., 11.],
       [12., 13., 14., 15., 16., 17., 12., 13., 14., 15., 16., 17.],
       [18., 19., 20., 21., 22., 23., 18., 19., 20., 21., 22., 23.],
       [24., 25., 26., 27., 28., 29., 24., 25., 26., 27., 28., 29.],
       [30., 31., 32., 33., 34., 35., 30., 31., 32., 33., 34., 35.],
       [ 0.,  1.,  2.,  3.,  4.,  5.,  0.,  1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10., 11.,  6.,  7.,  8.,  9., 10., 11.],
       [12., 13., 14., 15., 16., 17., 12., 13., 14., 15., 16., 17.],
       [18., 19., 20., 21., 22., 23., 18., 19., 20., 21., 22., 23.],
       [24., 25., 26., 27., 28., 29., 24., 25., 26., 27., 28., 29.],
       [30., 31., 32., 33., 34., 35., 30., 31., 32., 33., 34., 35.]])